apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: persistnet-webapp
  labels:
    app: persistent-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: persistent-webapp
  template:
    metadata:
      labels:
        app: persistent-webapp
    spec:
      containers:
      - name: persistent-webapp
        image: vikramsardeshpande/persistent-web-app:latest
        ports:
        - containerPort: 8080
